name: hello-workflow
on: push

jobs:
    job1:
        name: Job ONe
        runs-on: ubuntu-latest
        steps:
            - name: Step One
              uses: actions/checkout@v2
            - name: Step Two
              run: echo "Hello world"
    job2:
        name: Job Two
        runs-on: windows-latest
        steps:
            - name: Step1
              uses: actions/checkout@v2
            - name: Step 2
              run: "Get-ChildItem Env: | Sort-Object Name"
    job3:
        name: job Three
        runs-on: macos-latest
        steps:
            - name: Step1
              uses: actions/checkout@v2
            - name: Step 2
              run: env | sort
    job4:
        name: job Four
        runs-on: ubuntu-latest
        needs: [job1, job2, job3]
        steps:
            - name: Depends Job
              run: echo "Job 4 depends on Job 1,2,3"
